export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const FETCH_CHARACTERS_START = 'FETCH_CHARACTERS_START';
export const FETCH_CHARACTERS_SUCCESS = 'FETCH_CHARACTERS_SUCCESS';
export const FETCH_CHARACTERS_FAIL = 'FETCH_CHARACTERS_FAIL';
export const GET_CHARACTER_INFO = 'GET_CHARACTER_INFO';
export const GET_CHARACTER_INFO_START = 'GET_CHARACTER_INFO_START'
export const GET_CHARACTER_INFO_SUCCESS = 'GET_CHARACTER_INFO_SUCCESS'
export const GET_CHARACTER_INFO_FAIL = 'GET_CHARACTER_INFO_FAIL';
